getopt zamiast getopts

diff --git a/SHELL02/arg2 b/SHELL02/arg2
--- a/SHELL02/arg2
+++ b/SHELL02/arg2
@@ -7,46 +7,48 @@
 # Program 2
 set -e
 
-# sprawdzanie czy nie ma help
-for arg in "$@"; do
-    if [[ $arg != -* ]] ; then
-        break
-    elif [[ "$arg" == "--help" ]]; then
-        echo "help"
-        exit 0
-    fi
-done
+## parsowanie linii argumentow
+OPTS=$(getopt -o ioqabcdefghijklmnoprstuvwxyz --long help -n 'arg2' -- "$@")
+
+if [ $? -ne 0 ]; then
+  echo "Failed to parse options" >&2
+  exit 1
+fi
+
+eval set -- "$OPTS"
+
 
 options=($(printf '0 %.0s' {1..26}))
 
 # sprawdzenie obecnych flag opcji
 # i zaznaczenie tego w tablicy
-while getopts ":i:o:qabcdefghijklmnoprstuvwxyz" flag; do
-    case "$flag" in
-        q)
+while true; do
+    case "$1" in
+        --help)
+            echo "help"
+            exit 2
+            ;;
+        -q)
             # jesli jest -q zakonczenie programu
             echo "Unsupported option: -q"
-            exit 1
+            exit 3
             ;;
-        i)
+        -i)
             # jesli jest opcja -i zapamietujemy nazwe pliku
-            options[$(( $(printf "%d" "'$flag") - 97 ))]=1
-            inputFile="$OPTARG"
+            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
+            inputFile="$2"
+            shift 2
             ;;
-        o)
+        -o)
             # jesli jest opcja -o zapamietujemy nazwe pliku
-            options[$(( $(printf "%d" "'$flag") - 97 ))]=1
-            outputFile="$OPTARG"
+            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
+            outputFile="$2"
+            shift 2
             ;;
-        [a-hj-np-z])
-            options[$(( $(printf "%d" "'$flag") - 97 ))]=1
+        *)
+            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
             ;;
-        :)
-            # brak nazwy pliku dla -i -o
-            echo "-i -o options require a filename"
-            exit 1
-            ;;
-    esac
+  esac
 done
 
 # jako nazwa pliku zostala wczytana flaga
@@ -72,12 +74,12 @@ for ((i = 0; i < 26; i++)); do
 done
 
 # wypisanie argumentow
-argNum=$#
-optNum=$OPTIND
-if (( $((argNum - optNum + 1)) > 0 )) ; then
-    echo "Arguments are:"
-    for i in $(seq $optNum $argNum) ; do
-        ind=$((i - optNum + 1))
-        echo "\$${ind}=${!i}"
-    done
-fi
+# argNum=$#
+# optNum=$OPTIND
+# if (( $((argNum - optNum + 1)) > 0 )) ; then
+#     echo "Arguments are:"
+#     for i in $(seq $optNum $argNum) ; do
+#         ind=$((i - optNum + 1))
+#         echo "\$${ind}=${!i}"
+#     done
+# fi
