--

diff --git a/SHELL02/arg2 b/SHELL02/arg2
--- a/SHELL02/arg2
+++ b/SHELL02/arg2
@@ -7,18 +7,18 @@
 # Program 2
 set -e
 
-## parsowanie linii argumentow
-OPTS=$(getopt -o ioqabcdefghijklmnoprstuvwxyz --long help -n 'arg2' -- "$@")
+# parsowanie argumentow getopt
+SHORT_OPTS=":i:o:qabcdefghijklmnoprstuvwxyz"
+LONG_OPTS="help"
 
-if [ $? -ne 0 ]; then
-  echo "Failed to parse options" >&2
-  exit 1
-fi
-
-eval set -- "$OPTS"
+PARSED=$(getopt --options="$SHORT_OPTS" --longoptions="$LONG_OPTS" --name "$0" -- "$@") || exit 1
+eval set -- "$PARSED"
 
 
 options=($(printf '0 %.0s' {1..26}))
+inputFile=""
+outputFile=""
+qPresent=0
 
 # sprawdzenie obecnych flag opcji
 # i zaznaczenie tego w tablicy
@@ -26,30 +26,43 @@ while true; do
     case "$1" in
         --help)
             echo "help"
-            exit 2
+            exit 1
             ;;
         -q)
-            # jesli jest -q zakonczenie programu
-            echo "Unsupported option: -q"
-            exit 3
+            qPresent=1
+            shift
             ;;
         -i)
-            # jesli jest opcja -i zapamietujemy nazwe pliku
-            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
+            options[$(( $(printf "%d" "'i") - 97 ))]=1
             inputFile="$2"
             shift 2
             ;;
         -o)
-            # jesli jest opcja -o zapamietujemy nazwe pliku
-            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
+            options[$(( $(printf "%d" "'o") - 97 ))]=1
             outputFile="$2"
             shift 2
             ;;
+        -[a-hj-np-z])
+            flag="${1:1}"
+            options[$(( $(printf "%d" "'$flag") - 97 ))]=1
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
         *)
-            options[$(( $(printf "%d" "'${1:1}") - 97 ))]=1
+            echo "Internal error: $1"
+            exit 99
             ;;
   esac
 done
+
+# wypisanie dla opcji q
+if (($qPresent == 1)) ; then
+    echo "Unsupported option: -q"
+    exit 2
+fi
 
 # jako nazwa pliku zostala wczytana flaga
 if [[ $inputFile == -* || $outputFile == -* ]] ; then
